### ISSUE TITLE
Unresponsive-MAJOR-issue

### ISSUE THREAD

**Issue by Umam27** [Akashbhoi/Cabsharing#11]
The website was not operable when opened on different screen-sizes, The website was not responsive on any of its interface making it difficult to use. Since this website is for cab-booking, it will be of no use if there is a need to open laptop or bigger screen devices everytime to operate it. Please look into this issue as it makes the application very difficult to operate on mobiles.

**Comment by Akashbhoi** [comment]
we will implement this for different screen size including mobile device soon
