### ISSUE TITLE
The Driver's login changes to a Student's login 

### ISSUE THREAD

**Issue by Maurya73J** [Akashbhoi/Cabsharing#14]
On login in as a driver first, the page for the driver will be open but ongoing to profile, and clicking on the profile button multiple times and then going back to the home page by clicking the logo button will direct to the student's home page.

**Comment by Maurya73J** [comment]
After doing the above comments step and booking our own cab, a copy of Driver tile is created with random phone number, number plate, etc... but with same email.

**Comment by Rmukati1** [comment]
solved
