### ISSUE TITLE
Error-book-cab

### ISSUE THREAD

**Issue by Umam27** [Akashbhoi/Cabsharing#8]
I filled the travelling form, the details of this form was showing in the my-journeys tab. There was a button book-cab. On clicking it, it took me to a page showing many cab drivers, all showing available. When I clicked on any of them, it took me back to my-journeys page, but this time all the details was not there and no cab was booked. This is a bug where all the details was lost and no cab was booked even after booking one.

**Comment by Rmukati1** [comment]
solved and on clicking the book button request is sent to the driver if he/she accepts it then booking is done.
